apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
  namespace: kwikkoder
spec:
  secretName: tls-secret
  dnsNames:
    - kwikkoder.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kwikkoder.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer